

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "./main"] # Đợi db sẵn sàng rồi mới chạy app

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data/
  
  db-test:
    image: postgres:14-alpine
    container_name: todo_db_test # Tên container riêng
    env_file:
      - .env.test # <-- QUAN TRỌNG: Sử dụng file env.test
    ports:
      - "5434:5432" # <-- QUAN TRỌNG: Expose ra một port khác (5434)
    volumes:
      - postgres_test_data:/var/lib/postgresql/data # Volume dữ liệu riêng
    restart: always

volumes:
  postgres_dev_data:
  postgres_test_data: