basePath: /api/v1
definitions:
  dto.CreateTodoDTO:
    properties:
      title:
        type: string
    required:
    - title
    type: object
  dto.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  dto.RegisterRequest:
    properties:
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  dto.TokenRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  dto.TokenResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  dto.UpdateTodoDTO:
    properties:
      completed:
        type: boolean
      title:
        type: string
    required:
    - title
    type: object
  model.Todo:
    properties:
      completed:
        type: boolean
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Một API đơn giản để quản lý danh sách công việc.
  title: Todo List API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TokenResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Đăng nhập
      tags:
      - auth
  /auth/logout:
    post:
      consumes:
      - application/json
      parameters:
      - description: Refresh token to revoke
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/dto.TokenRequest'
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Đăng xuất và thu hồi refresh token
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      parameters:
      - description: Refresh token
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/dto.TokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TokenResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Refresh access token
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: User registration info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Đăng kí người dùng mới
      tags:
      - auth
  /todos:
    get:
      description: Lấy tất cả công việc trong danh sách
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Todo'
            type: array
      security:
      - BearerAuth: []
      summary: Lấy danh sách công việc
      tags:
      - todos
    post:
      consumes:
      - application/json
      description: Thêm một công việc mới vào danh sách với trạng thái mặc định là
        chưa hoàn thành
      parameters:
      - description: Chỉ cần nhập tiêu đề công việc
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/dto.CreateTodoDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Todo'
      security:
      - BearerAuth: []
      summary: Tạo một công việc mới
      tags:
      - todos
  /todos/{id}:
    delete:
      description: Xóa một công việc khỏi danh sách
      parameters:
      - description: ID Công việc
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Xóa một công việc
      tags:
      - todos
    get:
      description: Lấy thông tin chi tiết của một công việc
      parameters:
      - description: ID Công việc
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Todo'
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Lấy một công việc theo ID
      tags:
      - todos
    put:
      consumes:
      - application/json
      description: Cập nhật thông tin của một công việc đã có
      parameters:
      - description: ID Công việc
        in: path
        name: id
        required: true
        type: integer
      - description: Thông tin cập nhật
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateTodoDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Todo'
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Cập nhật một công việc
      tags:
      - todos
securityDefinitions:
  BearerAuth:
    description: Type "your-secret-api-key" to get access
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
